[std]
name = "python-eval"
version = "0.1.1"
description = "Python interpreter"


[std.capabilities."wasi:filesystem"]
description = "Executes user Python which may touch arbitrary filesystem paths."

[[std.capabilities."wasi:filesystem".allow]]
path = "**"
mode = "rw"
