[project]
name = "python-eval"
version = "0.1.0"
description = "Python interpreter"
requires-python = ">=3.14"
dependencies = [
    "act-sdk>=0.1.0",
]

[dependency-groups]
dev = [
    "componentize-py>=0.22.1",
    "ruff>=0.15.8",
]

[tool.uv.sources]
act-sdk = { git = "https://github.com/actcore/act-sdk-py.git" }
