name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: astral-sh/setup-uv@v6
      - uses: extractions/setup-just@v3
      - uses: taiki-e/cache-cargo-install-action@v3
        with:
          tool: wasm-custom-section
      - uses: taiki-e/cache-cargo-install-action@v3
        with:
          tool: wasm-tools
      - name: Build
        run: just build
      - uses: actions/upload-artifact@v7
        with:
          name: component.wasm
          path: python-interpreter.wasm

  e2e:
    name: E2E Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v4
        with:
          name: component.wasm
      - uses: actcore/act-cli/setup@main
      - uses: taiki-e/cache-cargo-install-action@v3
        with:
          tool: hurl
      - name: Run e2e tests
        run: |
          act serve python-interpreter.wasm --listen "[::1]:3456" &
          npx wait-on http://[::1]:3456/info
          hurl --test --variable "port=3456" e2e/*.hurl
          kill $!
